# Generated by Django 5.2.7 on 2025-11-01 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre court du bien (ex: Belle maison 3 chambres)', max_length=255)),
                ('description', models.TextField(help_text='Description complète du bien')),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix en FCFA', max_digits=12)),
                ('category', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('terrain', 'Terrain')], default='maison', max_length=50)),
                ('location', models.CharField(help_text='Localisation géographique du bien', max_length=255)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
