# Generated by Django 5.2.7 on 2025-11-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(help_text='Description détaillée du bien'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(help_text='Ville ou quartier du bien', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Prix du bien en FCFA', max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(help_text='Titre du bien (ex: Villa 4 chambres)', max_length=255),
        ),
    ]
